// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4TmmgYci423CMKXYEWXBzXGQwaLUj3Bc',
    appId: '1:817400347390:web:766cbfa6664fc1a7cd03af',
    messagingSenderId: '817400347390',
    projectId: 'crave-chat-app',
    authDomain: 'crave-chat-app.firebaseapp.com',
    storageBucket: 'crave-chat-app.appspot.com',
    measurementId: 'G-SGSG71JXSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdqLJn5dmdhjad_VAJ2ii053yht55tRQ',
    appId: '1:817400347390:android:765fd889d527deb9cd03af',
    messagingSenderId: '817400347390',
    projectId: 'crave-chat-app',
    storageBucket: 'crave-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrPZJLwN09-02NvDRT4YwFjqmgFV-QhEg',
    appId: '1:817400347390:ios:4cc8ee87449e922ccd03af',
    messagingSenderId: '817400347390',
    projectId: 'crave-chat-app',
    storageBucket: 'crave-chat-app.appspot.com',
    androidClientId: '817400347390-cdh6bsqr4h7ofqvktl84knhl8e54mprh.apps.googleusercontent.com',
    iosClientId: '817400347390-r963linqhhrlf1n6opr266r67mek7vi4.apps.googleusercontent.com',
    iosBundleId: 'com.wbdigital.crave',
  );
}
